//$file${.::period_high.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: real-time.qm
// File:  ${.::period_high.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::period_high.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"               // QP/C real-time event framework
#include "bsp.h"               // Board Support Package
#include "qm.h"               // Application interface

//$declare${AOs::PeriodHigh} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::PeriodHigh} .........................................................
typedef struct PeriodHigh {
// protected:
    QMActive super;

// public:
    QTimeEvt te;
    PeriodicSpecEvt periodic_evt;
} PeriodHigh;

extern PeriodHigh PeriodHigh_inst;

// protected:
static QState PeriodHigh_initial(PeriodHigh * const me, void const * const par);
static QState PeriodHigh_active  (PeriodHigh * const me, QEvt const * const e);
static QMState const PeriodHigh_active_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&PeriodHigh_active),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::PeriodHigh} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Q_DEFINE_THIS_MODULE("periodic_high")

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::PeriodHigh_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::PeriodHigh_ctor} .................................................
void PeriodHigh_ctor(void) {
    PeriodHigh * const me = &PeriodHigh_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&PeriodHigh_initial));
    QTimeEvt_ctorX(&me->te, (QActive *)me, TIMEOUT_SIG, 0U);
}
//$enddef${Shared::PeriodHigh_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AO_Period_High} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Period_High} ..................................................
QActive * const AO_Period_High = (QActive *)&PeriodHigh_inst;
//$enddef${Shared::AO_Period_High} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::PeriodHigh} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::PeriodHigh} .........................................................
PeriodHigh PeriodHigh_inst;

//${AOs::PeriodHigh::SM} .....................................................
static QState PeriodHigh_initial(PeriodHigh * const me, void const * const par) {
    //${AOs::PeriodHigh::SM::initial}
    // the initial event must be provided and must be WORKLOAD_SIG
    QEvt const *e =  (QEvt const *)par;

    Q_REQUIRE_ID(300, (e != (QEvt const *)0)
                 && (e->sig == PERIODIC_SPEC_SIG));
    QTimeEvt_armX(&me->te,
        Q_EVT_CAST(PeriodicSpecEvt)->ticks,
        Q_EVT_CAST(PeriodicSpecEvt)->ticks);

    QS_FUN_DICTIONARY(&PeriodHigh_active);

    static QMTranActTable const tatbl_ = { // tran-action table
        &PeriodHigh_active_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::PeriodHigh::SM::active} .............................................
//${AOs::PeriodHigh::SM::active}
static QState PeriodHigh_active(PeriodHigh * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::PeriodHigh::SM::active::TIMEOUT}
        case TIMEOUT_SIG: {
            task_high(me,&me->periodic_evt.inner_evt);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::PeriodHigh} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
