//$file${.::period_mid.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: real-time.qm
// File:  ${.::period_mid.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::period_mid.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"               // QP/C real-time event framework
#include "bsp.h"               // Board Support Package
#include "qm.h"               // Application interface

//$declare${AOs::PeriodMid} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::PeriodMid} ..........................................................
typedef struct PeriodMid {
// protected:
    QMActive super;

// public:
    QTimeEvt te;
    PeriodicSpecEvt periodic_evt;
} PeriodMid;

extern PeriodMid PeriodMid_inst;

// protected:
static QState PeriodMid_initial(PeriodMid * const me, void const * const par);
static QState PeriodMid_mid_active  (PeriodMid * const me, QEvt const * const e);
static QMState const PeriodMid_mid_active_s = {
    QM_STATE_NULL, // superstate (top)
    Q_STATE_CAST(&PeriodMid_mid_active),
    Q_ACTION_NULL, // no entry action
    Q_ACTION_NULL, // no exit action
    Q_ACTION_NULL  // no initial tran.
};
//$enddecl${AOs::PeriodMid} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Q_DEFINE_THIS_MODULE("periodic_mid")

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::PeriodMid_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::PeriodMid_ctor} ..................................................
void PeriodMid_ctor(void) {
    PeriodMid * const me = &PeriodMid_inst;
    QMActive_ctor(&me->super, Q_STATE_CAST(&PeriodMid_initial));
    QTimeEvt_ctorX(&me->te, (QActive *)me, TIMEOUT_SIG, 0U);
}
//$enddef${Shared::PeriodMid_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared::AO_Periodic_Mid} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Periodic_Mid} .................................................
QActive * const AO_Periodic_Mid = (QActive *)&PeriodMid_inst;
//$enddef${Shared::AO_Periodic_Mid} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::PeriodMid} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::PeriodMid} ..........................................................
PeriodMid PeriodMid_inst;

//${AOs::PeriodMid::SM} ......................................................
static QState PeriodMid_initial(PeriodMid * const me, void const * const par) {
    //${AOs::PeriodMid::SM::initial}

    QS_FUN_DICTIONARY(&PeriodMid_mid_active);

    static QMTranActTable const tatbl_ = { // tran-action table
        &PeriodMid_mid_active_s, // target state
        {
            Q_ACTION_NULL // zero terminator
        }
    };
    return QM_TRAN_INIT(&tatbl_);
}

//${AOs::PeriodMid::SM::mid_active} ..........................................
//${AOs::PeriodMid::SM::mid_active}
static QState PeriodMid_mid_active(PeriodMid * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::PeriodMid::SM::mid_active::RUN}
        case RUN_SIG: {
            task_mid(me, &me->periodic_evt.inner_evt);
            status_ = QM_HANDLED();
            break;
        }
        default: {
            status_ = QM_SUPER();
            break;
        }
    }
    return status_;
}
//$enddef${AOs::PeriodMid} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
